### ISSUE TITLE
Message Queue

### ISSUE THREAD

**Issue by amirhnajafiz** [official-stallion/stallion#24]
Golang channels are a bit shaky.

One solution is to use [Ergo](https://github.com/ergo-services/ergo).
Another solution was [Pyramid](https://github.com/amirhnajafiz/pyramid).

**Comment by gedw99** [comment]
What’s wrong with nats ??

**Comment by amirhnajafiz** [comment]
Dear @gedw99 there is nothing wrong with ```nats```, I just wanted to build a message queue myself.
I will run a benchmark after I implemented one and I will compare it to ```nats```, I it was not good enough,
I will switch to ```nats```.
